apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
spec:
  project: platform
  source:
    repoURL: https://github.com/polo871209/rpc.git
    targetRevision: main
    path: k8s/base/infra/postgres
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
