apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - postgres.yaml
labels:
  - pairs:
      app: postgres
      component: database
    includeSelectors: true
    includeTemplates: true
