apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgres
    component: database
  name: postgres
  namespace: rpc
stringData:
  DATABASE_URL: postgres://rpc_user:rpc_password@postgres.rpc.svc.cluster.local:5432/rpc?sslmode=disable
  HOST: postgres.rpc.svc.cluster.local
  POSTGRES_DB: rpc
  POSTGRES_PASSWORD: rpc_password
  POSTGRES_USER: rpc_user
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    component: database
  name: postgres
  namespace: rpc
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
    component: database
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
    component: database
  name: postgres
  namespace: rpc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
    component: database
  name: postgres
  namespace: rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      component: database
  template:
    metadata:
      labels:
        app: postgres
        component: database
    spec:
      containers:
        - env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: md5
          envFrom:
            - secretRef:
                name: postgres
          image: postgres:17
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - rpc_user
                - -d
                - rpc
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - rpc_user
                - -d
                - rpc
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres
