apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: migration
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/polo871209/arch-manifest.git
    targetRevision: main
    path: overlays/dev/migration
  destination:
    server: https://kubernetes.default.svc
    namespace: arch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
