apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: jaeger
spec:
  image: jaegertracing/jaeger:latest
  ports:
    - name: jaeger
      port: 16686
  env:
    - name: ES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elasticsearch-es-elastic-user
          key: elastic
  volumeMounts:
    - name: es-certs
      mountPath: /etc/ssl/certs/es-ca.crt
      subPath: ca.crt
      readOnly: true
  volumes:
    - name: es-certs
      secret:
        secretName: elasticsearch-es-http-certs-public
  config:
    # https://github.com/jaegertracing/jaeger/blob/v2.8.0/cmd/jaeger/config-spm.yaml
    service:
      extensions: [jaeger_storage, jaeger_query]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger_storage_exporter, spanmetrics]
        metrics/spanmetrics:
          receivers: [spanmetrics]
          exporters: [prometheus]
      telemetry:
        resource:
          service.name: jaeger
        metrics:
          level: detailed
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
        logs:
          level: INFO

    extensions:
      jaeger_query:
        storage:
          traces: some_storage
          metrics: some_metrics_storage
      jaeger_storage:
        backends:
          some_storage:
            memory:
              max_traces: 100000
        metric_backends:
          some_metrics_storage:
            prometheus:
              endpoint: http://prometheus-server.observability.svc.cluster.local:80
              normalize_calls: true
              normalize_duration: true

    connectors:
      spanmetrics:

    receivers:
      otlp:
        protocols:
          grpc:
          http:
            endpoint: "0.0.0.0:4318"

    processors:
      batch:

    exporters:
      jaeger_storage_exporter:
        trace_storage: some_storage
      prometheus:
        endpoint: "0.0.0.0:8889"
