apiVersion: v1
kind: ConfigMap
metadata:
  name: rpc-server
data:
  GRPC_PORT: "50051"
  MAX_RECV_MSG_SIZE: "4194304" # 4MB
  MAX_SEND_MSG_SIZE: "4194304" # 4MB
  ENABLE_REFLECTION: "true"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  CACHE_URL: "valkey://valkey.rpc.svc.cluster.local:6379"
  CACHE_MAX_CONNS: "10"
  CACHE_MIN_CONNS: "2"
  CACHE_MAX_IDLE_TIME: "300"
  CACHE_MAX_LIFETIME: "3600"
  DATABASE_HOST: "postgres-rw.postgres.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "rpc"
  DATABASE_USER: "rpc_user"
  DATABASE_SSL_MODE: "disable"
  DB_MAX_CONNS: "25"
  DB_MIN_CONNS: "5"
  DB_MAX_IDLE_TIME: "300"
  DB_MAX_LIFETIME: "3600"
  OTEL_SERVICE_NAME: "rpc-server"
  OTEL_SERVICE_VERSION: "1.0.0"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.jaeger.svc.cluster.local:4318"
  OTEL_ENABLED: "true"

