apiVersion: v1
kind: Secret
metadata:
  name: rpc-server
type: Opaque
stringData:
  DATABASE_USER: rpc_user
  DATABASE_PASSWORD: rpc_password
  DATABASE_NAME: rpc
  DATABASE_HOST: postgres-rw.rpc.svc.cluster.local
  DATABASE_PORT: "5432"
  DATABASE_SSL_MODE: disable
