apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rpc

resources:
  - namespace.yaml
  - postgres.yaml
  - valkey.yaml

labels:
  - pairs:
      project: rpc
    includeSelectors: true
    includeTemplates: true
