FROM cgr.dev/chainguard/wolfi-base:latest

RUN apk add --no-cache go git curl

ENV GOPATH=/go
ENV PATH="${GOPATH}/bin:${PATH}"

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

WORKDIR /migrations

COPY internal/database/migrations/ ./

CMD ["goose", "postgres", "${DATABASE_URL}", "up"]
