services:
  postgres:
    image: postgres:17
    container_name: rpc-postgres
    environment:
      POSTGRES_DB: rpc_dev
      POSTGRES_USER: rpc_user
      POSTGRES_PASSWORD: rpc_password
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rpc_user -d rpc_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: