apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 9.3.0
      chart: grafana
      helm:
        valueFiles:
          - $values/argocd/observability/grafana/grafana-values.yaml
    - repoURL: "https://github.com/polo871209/arch.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
