apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rpc
resources:
  - deploy.yaml
  - secret.yaml
labels:
  - pairs:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/component: db
      app.kubernetes.io/part-of: rpc
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
    includeTemplates: true
