apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: rpc
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 1
  bootstrap:
    initdb:
      database: rpc
      owner: rpc_user
      secret:
        name: postgres
  storage:
    size: 1Gi
