apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/infra/

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      environment: development
      tier: dev
