apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: rpc
stringData:
  DATABASE_URL: postgres://rpc_user:rpc_password@dev-postgres-service:5432/rpc_dev?sslmode=disable
  POSTGRES_DB: rpc_dev
  POSTGRES_PASSWORD: rpc_password
  POSTGRES_USER: rpc_user
