apiVersion: v1
kind: Secret
metadata:
  name: rpc-server-secret
type: Opaque
stringData:
  DATABASE_URL: postgres://rpc_user:rpc_password@postgres-service:5432/rpc_dev?sslmode=disable
  CACHE_URL: valkey://valkey-service:6379
  LOG_LEVEL: INFO
  SERVER_PORT: "50051"
