apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rpc
resources:
  - migration.yaml
labels:
  - pairs:
      app: rpc-server
      tier: db-migration
    includeSelectors: true
    includeTemplates: true
