apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  sources:
    - repoURL: https://helm.elastic.co
      chart: eck-stack
      targetRevision: 0.16.0
      helm:
        valueFiles:
          - $values/argocd/observability/efk/eck-stack-values.yaml
          - $values/argocd/observability/efk/eck-elasticsearch.yaml
          - $values/argocd/observability/efk/eck-kibana.yaml
    - repoURL: "https://github.com/polo871209/arch.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
