apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy.yaml
  - service.yaml
  - secret.yaml
labels:
  - pairs:
      app: rpc-client
      tier: rpc-client
    includeSelectors: true
    includeTemplates: true
