apiVersion: v1
kind: Secret
metadata:
  name: rpc-client
type: Opaque
stringData:
  GRPC_HOST: rpc-server.rpc.svc.cluster.local
  GRPC_PORT: "50051"
  API_HOST: 0.0.0.0
  API_PORT: "8000"
  LOG_LEVEL: INFO
  DEBUG: "false"
  API_RELOAD: "false"
