apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgres
          image: postgres:17
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until pg_isready -h $(DATABASE_HOST) -p 5432 -U $(DATABASE_USER); do
                echo "PostgreSQL is unavailable - sleeping"
                sleep 2
              done
              echo "PostgreSQL is ready"
          env:
            - name: PGPASSWORD
              value: rpc-password
            - name: DATABASE_USER
              value: rpc-user
            - name: DATABASE_HOST
              value: postgres-rw.postgres.svc.cluster.local
      containers:
        - name: migration
          image: rpc-migration:latest
          command:
            - goose
            - postgres
            - $(DATABASE_URL)
            - up
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rpc-server
                  key: DATABASE_URL
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m
