apiVersion: v1
kind: Namespace
metadata:
  name: arch
  labels:
    app.kubernetes.io/name: arch
    monitoring: prometheus
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    app.kubernetes.io/name: storage
    monitoring: prometheus
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/name: observability
    monitoring: prometheus
---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-stack
  labels:
    app.kubernetes.io/name: elastic-stack
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    app.kubernetes.io/name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
  labels:
    app.kubernetes.io/name: elastic-system
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger-operator
  labels:
    app.kubernetes.io/name: jaeger-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry-operator
  labels:
    app.kubernetes.io/name: opentelemetry-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: kiali-operator
  labels:
    name: kiali-operator
    app.kubernetes.io/name: kiali-operator
