apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-operator
spec:
  project: platform
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-operator
    targetRevision: 2.13.0
    helm:
      values: |
        cr:
          create: true
          namespace: istio-system
          spec:
            auth:
              strategy: anonymous
            external_services:
              prometheus:
                url: http://prometheus-server.observability.svc.cluster.local:80
              grafana:
                enabled: true
                url: http://grafana.observability.svc.cluster.local:80
                in_cluster_url: http://grafana.observability.svc.cluster.local:80
                auth:
                  type: none
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
