apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://helm.elastic.co
      chart: eck-stack
      targetRevision: 0.16.0
      helm:
        valueFiles:
          - $values/infra/eck/eck-stack-values.yaml
    - repoURL: "https://github.com/polo871209/rpc.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
