---
apiVersion: v1
kind: Secret
metadata:
  name: arch-user-credentials
  namespace: storage
type: Opaque
stringData:
  username: arch_user
  password: arch_password
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: arch
  namespace: storage
spec:
  name: arch
  rabbitmqClusterReference:
    name: default
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: arch-user
  namespace: storage
spec:
  tags:
    - management
    - policymaker
  rabbitmqClusterReference:
    name: default
  importCredentialsSecret:
    name: arch-user-credentials
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: arch-user-permission
  namespace: storage
spec:
  vhost: arch
  userReference:
    name: arch-user
  permissions:
    configure: ".*"
    read: ".*"
    write: ".*"
  rabbitmqClusterReference:
    name: default