# Development environment patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: rpc
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: rpc
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: grpc-server
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 200m
      initContainers:
      - name: wait-for-postgres
        command:
        - sh
        - -c
        - until pg_isready -h dev-postgres-service.rpc.svc.cluster.local -p 5432 -U rpc_user; do echo waiting for postgres; sleep 2; done;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-client
  namespace: rpc
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: fastapi-client
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 150m
      initContainers:
      - name: wait-for-grpc-server
        command:
        - sh
        - -c
        - until nc -z dev-grpc-server-service.rpc.svc.cluster.local 50051; do echo waiting for grpc server; sleep 2; done;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: rpc
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-postgres
        command:
        - sh
        - -c
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h dev-postgres-service.rpc.svc.cluster.local -p 5432 -U rpc_user; do
            echo "PostgreSQL is unavailable - sleeping"
            sleep 2
          done
          echo "PostgreSQL is ready"