apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patches.yaml
  - secret-patches.yaml

namePrefix: dev-

commonLabels:
  environment: development
  tier: dev