apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://cloudnative-pg.io/charts/
      chart: cloudnative-pg
      targetRevision: 0.25.0
      helm:
        valueFiles:
          - $values/infra/eck/cloudnative-pg/cloudnative-pg-values.yaml
    - repoURL: "https://github.com/polo871209/rpc.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/polo871209/rpc
    targetRevision: main
    path: infra/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
