apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rpc
resources:
  - rpc-client
  - rpc-server
labels:
  - pairs:
      project: rpc
    includeSelectors: true
    includeTemplates: true

