apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 25.21.0
      helm:
        valueFiles:
          - $values/infra/prometheus/prometheus-values.yaml
    - repoURL: "https://github.com/polo871209/rpc.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
