apiVersion: v1
kind: Secret
metadata:
  name: grpc-server-secret
  namespace: rpc
type: Opaque
stringData:
  DATABASE_URL: postgres://rpc_user:rpc_password@postgres-service.rpc.svc.cluster.local:5432/rpc_dev?sslmode=disable
  CACHE_URL: valkey://valkey-service.rpc.svc.cluster.local:6379
  LOG_LEVEL: INFO
  SERVER_PORT: "50051"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: rpc
  labels:
    app: grpc-server
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
        component: backend
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:17
        command:
        - sh
        - -c
        - until pg_isready -h postgres-service.rpc.svc.cluster.local -p 5432 -U rpc_user; do echo waiting for postgres; sleep 2; done;
      containers:
      - name: grpc-server
        image: localhost:5000/rpc-server:latest
        ports:
        - containerPort: 50051
          name: grpc
        envFrom:
        - secretRef:
            name: grpc-server-secret
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
        livenessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
  namespace: rpc
  labels:
    app: grpc-server
    component: backend
spec:
  selector:
    app: grpc-server
  ports:
  - port: 50051
    targetPort: 50051
    name: grpc
  type: ClusterIP