apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  sources:
    - repoURL: https://kiali.org/helm-charts
      chart: kiali-operator
      targetRevision: 2.13.0
      helm:
        valueFiles:
          - $values/infra/service-mesh/kiali/kiali-operator-values.yaml
    - repoURL: "https://github.com/polo871209/arch.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
