apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:8.0
          ports:
            - containerPort: 6379
              name: valkey
          command: ["valkey-server", "--appendonly", "yes"]
          volumeMounts:
            - name: valkey-storage
              mountPath: /data
          livenessProbe:
            exec:
              command: ["valkey-cli", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["valkey-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroup: 999
      volumes:
        - name: valkey-storage
          persistentVolumeClaim:
            claimName: valkey
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: tcp
  type: ClusterIP
